In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"c1":[0,0,0,0,0,0,0],
                  "c2":[0,0,1,1,1,0,0],
                  "c3":[0,1,1,0,0,1,0],
                   "c4":[0,1,1,0,1,1,0],
                  "c5":[0,0,1,1,0,1,0],
                  "c6":[0,0,0,0,0,0,0]})

In [3]:
df

c1  c2  c3  c4  c5  c6
0   0   0   0   0   0   0
1   0   0   1   1   0   0
2   0   1   1   1   1   0
3   0   1   0   0   1   0
4   0   1   0   1   0   0
5   0   0   1   1   1   0
6   0   0   0   0   0   0

In [4]:
df[1:3]

c1  c2  c3  c4  c5  c6
1   0   0   1   1   0   0
2   0   1   1   1   1   0

In [5]:
list_col = list(df.columns)

In [6]:
list_col

['c1', 'c2', 'c3', 'c4', 'c5', 'c6']

In [7]:
valH,valW = df.shape

In [8]:
valH,valW

(7, 6)

In [9]:
valH

7

In [11]:
dict_df = {}
for val_i in range(valH-3):
    tmp_list = []
    for val_j in range(valW-3):
        tmp_col = list_col[val_j:val_j+3]
        tmp_df = df[val_i:val_i+3][tmp_col]
        print(tmp_df)

   c1  c2  c3
0   0   0   0
1   0   0   1
2   0   1   1
   c2  c3  c4
0   0   0   0
1   0   1   1
2   1   1   1
   c3  c4  c5
0   0   0   0
1   1   1   0
2   1   1   1
   c1  c2  c3
1   0   0   1
2   0   1   1
3   0   1   0
   c2  c3  c4
1   0   1   1
2   1   1   1
3   1   0   0
   c3  c4  c5
1   1   1   0
2   1   1   1
3   0   0   1
   c1  c2  c3
2   0   1   1
3   0   1   0
4   0   1   0
   c2  c3  c4
2   1   1   1
3   1   0   0
4   1   0   1
   c3  c4  c5
2   1   1   1
3   0   0   1
4   0   1   0
   c1  c2  c3
3   0   1   0
4   0   1   0
5   0   0   1
   c2  c3  c4
3   1   0   0
4   1   0   1
5   0   1   1
   c3  c4  c5
3   0   0   1
4   0   1   0
5   1   1   1


In [14]:
tmp_df.dot(tmp_df.T)

3  4  5
3  1  0  1
4  0  1  1
5  1  1  3

In [15]:
tmp_df.T

3  4  5
c3  0  0  1
c4  0  1  1
c5  1  0  1

In [24]:
tmp_array=tmp_df.values

In [25]:
np.sum(tmp_array*tmp_array)

5

In [4]:
val_array = df.values

In [5]:
val_array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [18]:
val0 = np.array([1,2,3,4])

In [19]:
val0

array([1, 2, 3, 4])

In [20]:
val1 = np.array((1,2,3,1))

In [21]:
val1

array([1, 2, 3, 1])

In [22]:
val1*val0

array([1, 4, 9, 4])

In [23]:
np.sum(val1*val0)

18